-- ==========================================
-- TonTrac Clone Database Schema for Supabase
-- ==========================================
-- Copy and paste this script directly into your Supabase SQL Editor.
-- This defines all tables required by the Spring Boot backend JPA entities.

-- Drop tables if they exist to allow clean re-runs
DROP TABLE IF EXISTS weighbridge_ticket CASCADE;
DROP TABLE IF EXISTS weighbridge_order CASCADE;
DROP TABLE IF EXISTS vehicle CASCADE;
DROP TABLE IF EXISTS stockpile CASCADE;
DROP TABLE IF EXISTS site CASCADE;
DROP TABLE IF EXISTS haulier CASCADE;
DROP TABLE IF EXISTS driver CASCADE;
DROP TABLE IF EXISTS alert CASCADE;

-- 1. Alert Table
CREATE TABLE alert (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type VARCHAR(255),
    title VARCHAR(255),
    description TEXT,
    severity VARCHAR(50),
    time VARCHAR(50),
    is_read BOOLEAN,
    created_date TIMESTAMP WITHOUT TIME ZONE
);

-- 2. Driver Table
CREATE TABLE driver (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255),
    id_number VARCHAR(50),
    license_number VARCHAR(50),
    induction_status VARCHAR(50),
    medical_expiry_date TIMESTAMP WITHOUT TIME ZONE,
    training_expiry_date TIMESTAMP WITHOUT TIME ZONE,
    assigned_haulier VARCHAR(255),
    active BOOLEAN
);

-- 3. Haulier Table
CREATE TABLE haulier (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255),
    email VARCHAR(255),
    phone VARCHAR(50),
    compliance_status VARCHAR(50),
    active BOOLEAN
);

-- 4. Site Table
CREATE TABLE site (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255),
    type VARCHAR(50),
    latitude DOUBLE PRECISION,
    longitude DOUBLE PRECISION,
    operating_hours VARCHAR(255),
    access_rules TEXT
);

-- 5. Stockpile Table
CREATE TABLE stockpile (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255),
    product VARCHAR(255),
    tons DOUBLE PRECISION,
    capacity DOUBLE PRECISION,
    color VARCHAR(50)
);

-- 6. Vehicle Table
CREATE TABLE vehicle (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reg VARCHAR(50),
    fleet VARCHAR(255),
    haulier VARCHAR(255),
    type VARCHAR(50),
    max_legal_weight DOUBLE PRECISION,
    compliance_status VARCHAR(50),
    gps_device_id VARCHAR(100),
    active BOOLEAN
);

-- 7. Weighbridge Order Table
CREATE TABLE weighbridge_order (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id VARCHAR(255),
    type VARCHAR(50),
    product VARCHAR(255),
    target DOUBLE PRECISION,
    allocated DOUBLE PRECISION,
    client VARCHAR(255),
    status VARCHAR(50)
);

-- 8. Weighbridge Ticket Table
CREATE TABLE weighbridge_ticket (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ticket_id VARCHAR(255),
    reg VARCHAR(50),
    prod VARCHAR(255),
    gross DOUBLE PRECISION,
    net DOUBLE PRECISION,
    status VARCHAR(50),
    time VARCHAR(50),
    created_date TIMESTAMP WITHOUT TIME ZONE,
    mine_site VARCHAR(255),
    origin_weighbridge VARCHAR(255),
    destination VARCHAR(255),
    driver_name VARCHAR(255),
    trailer_reg VARCHAR(50),
    tare_weight DOUBLE PRECISION,
    gross_weight DOUBLE PRECISION,
    net_weight DOUBLE PRECISION,
    destination_weight DOUBLE PRECISION,
    variance DOUBLE PRECISION,
    reconciliation_status VARCHAR(50),
    rate_per_ton DOUBLE PRECISION,
    total_amount DOUBLE PRECISION,
    invoice_status VARCHAR(50)
);
